object AuroraKeycodeMapper {

    fun toAuroraKeyCode(a: String): Int {
        val yes = a.replace("key.keyboard.", "")
        when (yes) {
            "esc" -> return 0x01
            "1" -> return 0x02
            "2" -> return 0x03
            "3" -> return 0x04
            "4" -> return 0x05
            "5" -> return 0x06
            "6" -> return 0x07
            "7" -> return 0x08
            "8" -> return 0x09
            "9" -> return 0x0A
            "0" -> return 0x0B
            "minus" -> return 0x0C
            "equal" -> return 0x0D
            "backspace" -> return 0x0E
            "tab" -> return 0x0F
            "q" -> return 0x10
            "w" -> return 0x11
            "e" -> return 0x12
            "r" -> return 0x13
            "t" -> return 0x14
            "y" -> return 0x15
            "u" -> return 0x16
            "i" -> return 0x17
            "o" -> return 0x18
            "p" -> return 0x19
            "left.bracket" -> return 0x1A
            "right.bracket" -> return 0x1B
            "enter" -> return 0x1B
            "left.control" -> return 0x1D
            "a" -> return 0x1E
            "s" -> return 0x1F
            "d" -> return 0x20
            "f" -> return 0x21
            "g" -> return 0x22
            "h" -> return 0x23
            "j" -> return 0x24
            "k" -> return 0x25
            "l" -> return 0x26
            "semicolon" -> return 0x27
            "apostrophe" -> return 0x28
            "tilde" -> return 0x29 //???
            "left.shift" -> return 0x2A
            "backslash" -> return 0x2B
            "z" -> return 0x2C
            "x" -> return 0x2D
            "c" -> return 0x2E
            "v" -> return 0x2F
            "b" -> return 0x30
            "n" -> return 0x31
            "m" -> return 0x32
            "comma" -> return 0x33
            "period" -> return 0x34
            "slash" -> return 0x35
            "right.shift" -> return 0x36
            "keypad.multiply" -> return 0x37
            "left.alt" -> return 0x38
            "space" -> return 0x39
            "caps.lock" -> return 0x3A
            "f1" -> return 0x3B
            "f2" -> return 0x3C
            "f3" -> return 0x3D
            "f4" -> return 0x3E
            "f5" -> return 0x3F
            "f6" -> return 0x40
            "f7" -> return 0x41
            "f8" -> return 0x42
            "f9" -> return 0x43
            "f10" -> return 0x44
            "num.lock" -> return 0x45
            "scroll.lock" -> return 0x46
            "keypad.7" -> return 0x47
            "keypad.8" -> return 0x48
            "keypad.9" -> return 0x49
            "keypad.subtract" -> return 0x4A
            "keypad.4" -> return 0x4B
            "keypad.5" -> return 0x4C
            "keypad.6" -> return 0x4D
            "keypad.add" -> return 0x4E
            "keypad.1" -> return 0x4F
            "keypad.2" -> return 0x50
            "keypad.3" -> return 0x51
            "keypad.0" -> return 0x52
            "keypad.decimal" -> return 0x53
            "f11" -> return 0x57
            "f12" -> return 0x58
            "keypad.enter" -> return 0x9C
            "right.control" -> return 0x9D
            "keypad.divide" -> return 0xB5
            "right.alt" -> return 0xB8
            "pause" -> return 0xC5
            "home" -> return 0xC7
            "up" -> return 0xC8
            "page.up" -> return 0xC9
            "left" -> return 0xCB
            "right" -> return 0xCD
            "end" -> return 0xCF
            "down" -> return 0xCF
            "page.down" -> return 0xD1
            "insert" -> return 0xD2
            "delete" -> return 0xD3
            "left.win" -> return 0xDB
            else -> return 0x00
        }
    }
}