package com.project_aurora

object AuroraKeycodeMapper {

    fun toAuroraKeyCode(a: String): Int {
        when (a) {
            "key.keyboard.esc" -> return 0x01
            "key.keyboard.1" -> return 0x02
            "key.keyboard.2" -> return 0x03
            "key.keyboard.3" -> return 0x04
            "key.keyboard.4" -> return 0x05
            "key.keyboard.5" -> return 0x06
            "key.keyboard.6" -> return 0x07
            "key.keyboard.7" -> return 0x08
            "key.keyboard.8" -> return 0x09
            "key.keyboard.9" -> return 0x0A
            "key.keyboard.0" -> return 0x0B
            "key.keyboard.minus" -> return 0x0C
            "key.keyboard.equal" -> return 0x0D
            "key.keyboard.backspace" -> return 0x0E
            "key.keyboard.tab" -> return 0x0F
            "key.keyboard.q" -> return 0x10
            "key.keyboard.w" -> return 0x11
            "key.keyboard.e" -> return 0x12
            "key.keyboard.r" -> return 0x13
            "key.keyboard.t" -> return 0x14
            "key.keyboard.y" -> return 0x15
            "key.keyboard.u" -> return 0x16
            "key.keyboard.i" -> return 0x17
            "key.keyboard.o" -> return 0x18
            "key.keyboard.p" -> return 0x19
            "key.keyboard.left.bracket" -> return 0x1A
            "key.keyboard.right.bracket" -> return 0x1B
            "key.keyboard.enter" -> return 0x1B
            "key.keyboard.left.control" -> return 0x1D
            "key.keyboard.a" -> return 0x1E
            "key.keyboard.s" -> return 0x1F
            "key.keyboard.d" -> return 0x20
            "key.keyboard.f" -> return 0x21
            "key.keyboard.g" -> return 0x22
            "key.keyboard.h" -> return 0x23
            "key.keyboard.j" -> return 0x24
            "key.keyboard.k" -> return 0x25
            "key.keyboard.l" -> return 0x26
            "key.keyboard.semicolon" -> return 0x27
            "key.keyboard.apostrophe" -> return 0x28
            "key.keyboard.tilde" -> return 0x29 //???
            "key.keyboard.left.shift" -> return 0x2A
            "key.keyboard.backslash" -> return 0x2B
            "key.keyboard.z" -> return 0x2C
            "key.keyboard.x" -> return 0x2D
            "key.keyboard.c" -> return 0x2E
            "key.keyboard.v" -> return 0x2F
            "key.keyboard.b" -> return 0x30
            "key.keyboard.n" -> return 0x31
            "key.keyboard.m" -> return 0x32
            "key.keyboard.comma" -> return 0x33
            "key.keyboard.period" -> return 0x34
            "key.keyboard.slash" -> return 0x35
            "key.keyboard.right.shift" -> return 0x36
            "key.keyboard.keypad.multiply" -> return 0x37
            "key.keyboard.left.alt" -> return 0x38
            "key.keyboard.space" -> return 0x39
            "key.keyboard.caps.lock" -> return 0x3A
            "key.keyboard.f1" -> return 0x3B
            "key.keyboard.f2" -> return 0x3C
            "key.keyboard.f3" -> return 0x3D
            "key.keyboard.f4" -> return 0x3E
            "key.keyboard.f5" -> return 0x3F
            "key.keyboard.f6" -> return 0x40
            "key.keyboard.f7" -> return 0x41
            "key.keyboard.f8" -> return 0x42
            "key.keyboard.f9" -> return 0x43
            "key.keyboard.f10" -> return 0x44
            "key.keyboard.num.lock" -> return 0x45
            "key.keyboard.scroll.lock" -> return 0x46
            "key.keyboard.keypad.7" -> return 0x47
            "key.keyboard.keypad.8" -> return 0x48
            "key.keyboard.keypad.9" -> return 0x49
            "key.keyboard.keypad.subtract" -> return 0x4A
            "key.keyboard.keypad.4" -> return 0x4B
            "key.keyboard.keypad.5" -> return 0x4C
            "key.keyboard.keypad.6" -> return 0x4D
            "key.keyboard.keypad.add" -> return 0x4E
            "key.keyboard.keypad.1" -> return 0x4F
            "key.keyboard.keypad.2" -> return 0x50
            "key.keyboard.keypad.3" -> return 0x51
            "key.keyboard.keypad.0" -> return 0x52
            "key.keyboard.keypad.decimal" -> return 0x53
            "key.keyboard.f11" -> return 0x57
            "key.keyboard.f12" -> return 0x58
            "key.keyboard.keypad.enter" -> return 0x9C
            "key.keyboard.right.control" -> return 0x9D
            "key.keyboard.keypad.divide" -> return 0xB5
            "key.keyboard.right.alt" -> return 0xB8
            "key.keyboard.pause" -> return 0xC5
            "key.keyboard.home" -> return 0xC7
            "key.keyboard.up" -> return 0xC8
            "key.keyboard.page.up" -> return 0xC9
            "key.keyboard.left" -> return 0xCB
            "key.keyboard.right" -> return 0xCD
            "key.keyboard.end" -> return 0xCF
            "key.keyboard.down" -> return 0xCF
            "key.keyboard.page.down" -> return 0xD1
            "key.keyboard.insert" -> return 0xD2
            "key.keyboard.delete" -> return 0xD3
            "key.keyboard.left.win" -> return 0xDB
            else -> return 0x00
        }
    }
}